language: java

jdk:
  - openjdk8 

script:
  - mvn install:install-file -Dfile=ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar -Dsonar.projectKey=revaturelabs_caliber-2-assessment-service -Dsonar.organization=revaturelabs-screenforce -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a658fd13b7b4deefaa2c6ff8742ccbbb4f449da1
