version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Building Catagory Service 
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - BUILD_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
  build:
    commands:
      - echo Building Maven Project
      - mvn install:install-file -Dfile=src/main/resources/ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar
      - mvn clean
      - mvn install -DskipTests
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Using Spring Profile $SPRING_ENV
      - docker build -t $SERVICE_NAME:$BUILD_ID --build-arg CATEGORY_CLIENT=$CATEGORY_CLIENT --build-arg BATCH_CLIENT=$BATCH_CLIENT --build-arg USER_CLIENT=$USER_CLIENT --build-arg CONFIG_URL=$CONFIG_URL --build-arg JAR_FILE=caliber-quality-audit-service-0.0.1-SNAPSHOT.jar --build-arg SPRING_ENV=$SPRING_ENV --build-arg DB_USER=$DB_USER --build-arg DB_PASS=$DB_PASS --build-arg DB_URL=$DB_URL .
      - docker tag $SERVICE_NAME:$BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
      - echo Writing image base file...
      - printf '[{"name":"%s","imageUri":"%s", "cpu":220, "memory":450}]' $SERVICE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - 'Dockerfile'
    - 'target/caliber-quality-audit-service-0.0.1-SNAPSHOT.jar'
