spring:
  application:
    name: location

eureka:
  client:
#     service-url:
#       default-zone: ${EUREKA_HOME}
    fetch-registry: false
    register-with-eureka: false
    
server:
  port: 9075
